In [ ]:
x = 25
x

25

In [ ]:
type(x)

int

In [ ]:
y =3
y

3

In [ ]:
type(y)

int

In [ ]:
py_sum = x+y
py_sum

28

Scalars in Pytorch

In [ ]:
import torch

In [ ]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [ ]:
x_pt.shape

torch.Size([])

**scalars in Tensorflow**

In [ ]:
import tensorflow as tf

In [ ]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [ ]:
x_tf.shape #it gonna be empty since this is a scalar, dimension zero

TensorShape([])

In [ ]:
y_tf = tf.Variable(3, dtype = tf.int16)

In [ ]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [ ]:
tf_sum= tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [ ]:
tf_sum.numpy()

28

In [ ]:
type(tf_sum.numpy())

numpy.int16

**Vectors and vectors transposition**

In [ ]:
import numpy as np


In [ ]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [ ]:
len(x)

3

In [ ]:
x.shape

(3,)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x[0]

25

**Transposing a vector**

In [ ]:
y = np.array([[25,2,5]])
y

array([[25,  2,  5]])

In [ ]:
y.shape

(1, 3)

In [ ]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [ ]:
y_t.shape

(3, 1)

In [ ]:
#We can re-transpose a transposed vector
y_u=y_t.T
y_u

array([[25,  2,  5]])

**Vectors in Pytorch and Tensorflow**

In [ ]:
import torch
import tensorflow as tf


In [ ]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [ ]:
x_tf = tf.Variable([25,2,5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

**Norms and unit vectors**

In [ ]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [ ]:
# Computing the L2 norm (euclidean distance)
np.linalg.norm(x)

25.573423705088842

In [ ]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

**L1 NORM** This kind of norm encourages the sparcity leading to the selection of the most relevant features in a ML model


In [ ]:
x

array([25,  2,  5])

In [ ]:
(25+2+5)

32

**Squared L^2 norm**

In [ ]:
x

array([25,  2,  5])

In [ ]:
(25**2 + 2**2 + 5**2)

654

In [ ]:
np.dot(x,x)

654

**Max Norm**

In [ ]:
x

array([25,  2,  5])

In [ ]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

# Matrices : 2D tensors vectors

In [ ]:
import numpy as np

In [ ]:
# Numpy: nested lists
X = np.array([[25,2],[5, 26], [3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
X.shape

(3, 2)

In [ ]:
X.size

6

In [ ]:
# Select a particular column
X[:,0]

array([25,  5,  3])

In [ ]:
X[:,1]

array([ 2, 26,  7])

In [ ]:
X[1:,]

array([[ 5, 26],
       [ 3,  7]])

In [ ]:
Y = np.array([[3,2,4,6], [6,5,7,8], [10,11,12,13]])
Y

array([[ 3,  2,  4,  6],
       [ 6,  5,  7,  8],
       [10, 11, 12, 13]])

In [ ]:
Y = Y[:, 1:2]
Y

array([[ 2],
       [ 5],
       [11]])

# Matrices in Pytorch

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[25,2], [5,26], [3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [ ]:
X_pt.shape

torch.Size([3, 2])

In [ ]:
X_pt[1, :]

tensor([ 5, 26])

# Matrices in Tensorflow


In [ ]:
import tensorflow as tf

In [ ]:
X_tf = tf.Variable([[25,2], [5,26], [3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [ ]:
#to ask the dimensionality
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

# Higher- Rank tensors

In [ ]:
# For instance in the MNIST dataset we have a batch of 32 images
# 28 pixels per width and height and 3 RGB colours
images_pt = torch.zeros([32,28,28,3])
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [ ]:
# Tensorflow
images_tf = tf.zeros([32,28,28,3])
images_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   